import { NewsItem, DeliveryProfiles } from "./types";

// Placeholder feed — shaped to match Tara's real /Users/mac/Tara/data/today.json
// worldNews[] schema exactly, so it can be swapped for the live pipeline output.
export const newsFeed: NewsItem[] = [
  {
    region: "North America",
    currency: "USD",
    headline: "US CPI YoY rises to 3.2% vs 3.0% expected",
    detail: "Core CPI also surprised to upside, supporting Fed hawkishness.",
    source: "Reuters",
    url: "https://www.reuters.com/markets/us-cpi-july-2026-placeholder",
    hot: true,
    impact: "negative",
    impactNote: "Higher inflation dims rate cut odds",
    strength: 4,
    firstSeen: "2026-07-12",
  },
  {
    region: "Europe",
    currency: "EUR",
    headline: "Eurozone PMI Composite slips to 49.1",
    detail: "Manufacturing weakness persists while services hold near flat.",
    source: "FXStreet",
    url: "https://www.fxstreet.com/eurozone-pmi-july-2026-placeholder",
    hot: false,
    impact: "negative",
    impactNote: "Contraction signals weigh on euro",
    strength: 3,
    firstSeen: "2026-07-13",
  },
  {
    region: "Europe",
    currency: "GBP",
    headline: "BOE holds rates at 4.50% as forecast",
    detail: "Vote split 6-3 with dissenters calling for cut.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/boe-decision-july-2026-placeholder",
    hot: false,
    impact: "neutral",
    impactNote: "No fresh policy signal given",
    strength: 2,
    firstSeen: "2026-07-14",
  },
  {
    region: "Asia",
    currency: "JPY",
    headline: "Japan PPI accelerates to 2.8% YoY",
    detail: "Input costs climb, pressuring BOJ normalization narrative.",
    source: "Investing",
    url: "https://www.investing.com/japan-ppi-july-2026-placeholder",
    hot: false,
    impact: "positive",
    impactNote: "Supports gradual yen tightening bias",
    strength: 3,
    firstSeen: "2026-07-15",
  },
  {
    region: "Asia",
    currency: "AUD",
    headline: "Australia Retail Sales +0.6% MoM beat",
    detail: "Strong household spend offsets soft business sentiment.",
    source: "ForexLive",
    url: "https://www.forexlive.com/aud-retail-sales-july-2026-placeholder",
    hot: true,
    impact: "positive",
    impactNote: "Aussie bids on consumption resilience",
    strength: 4,
    firstSeen: "2026-07-16",
  },
  {
    region: "North America",
    currency: "USD",
    headline: "US NFP prints 210k vs 190k expected",
    detail: "Unemployment steady at 4.1%, wages in line.",
    source: "Reuters",
    url: "https://www.reuters.com/us-nfp-july-2026-placeholder",
    hot: true,
    impact: "positive",
    impactNote: "Solid labor market backs USD",
    strength: 5,
    firstSeen: "2026-07-17",
  },
  {
    region: "Europe",
    currency: "EUR",
    headline: "Germany ZEW sentiment improves to 35.0",
    detail: "Optimism on export demand lifts morale moderately.",
    source: "FXStreet",
    url: "https://www.fxstreet.com/ezew-july-2026-placeholder",
    hot: false,
    impact: "positive",
    impactNote: "Mild euro support from sentiment",
    strength: 2,
    firstSeen: "2026-07-18",
  },
  {
    region: "Asia",
    currency: "JPY",
    headline: "BOJ maintains stance, trims CPI outlook",
    detail: "Caution on overseas risks cited in statement.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/boj-july-2026-placeholder",
    hot: false,
    impact: "negative",
    impactNote: "Yen softens on dovish tilt",
    strength: 3,
    firstSeen: "2026-07-19",
  },
  {
    region: "North America",
    currency: "USD",
    headline: "US PPI flat MoM, services cost eases",
    detail: "Wholesale inflation cools, contrasting CPI surprise.",
    source: "Investing",
    url: "https://www.investing.com/us-ppi-july-2026-placeholder",
    hot: false,
    impact: "neutral",
    impactNote: "Mixed bag leaves USD directionless",
    strength: 2,
    firstSeen: "2026-07-20",
  },
  {
    region: "Asia",
    currency: "AUD",
    headline: "RBA flags patient hold, growth muted",
    detail: "Governor notes uneven recovery in sectors.",
    source: "ForexLive",
    url: "https://www.forexlive.com/rba-july-2026-placeholder",
    hot: false,
    impact: "neutral",
    impactNote: "AUD range bound post statement",
    strength: 3,
    firstSeen: "2026-07-21",
  },
];

// Placeholder — shaped to match Tara's real /Users/mac/Tara/data/profiles.json schema.
export const deliveryProfiles: DeliveryProfiles = {
  am: {
    label: "New York AM",
    windows: ["AM1 7:00-8:30", "AM2 8:30-10:00", "AM3 10:00-11:30"],
    profiles: [
      {
        id: "am-1",
        num: 1,
        title: "Quick Open Reversal",
        marketConditions: ["Low liquidity at open", "Overnight gap present", "News quiet pre-data"],
        keyCharacteristics: ["Fast fakeout then reverse", "Tight opening range", "Volume spike trap"],
        traderFocus: ["Watch opening sweep", "Fade early extremes", "Use 5m confirm"],
      },
      {
        id: "am-2",
        num: 2,
        title: "Classic AMD Delivery",
        marketConditions: ["Steady Asian range break", "London close aligned", "Data due 8:30"],
        keyCharacteristics: ["Accumulation then markup", "Clean displacement candle", "Retrace shallow"],
        traderFocus: ["Track London high", "Enter on pullback", "Target prior day"],
      },
      {
        id: "am-3",
        num: 3,
        title: "Trend Trap & Snap Reversal",
        marketConditions: ["Late AM exhaustion", "False breakout common", "Volatility compressing"],
        keyCharacteristics: ["Trend lure then snap", "Wick reversal signal", "Momentum flush"],
        traderFocus: ["Avoid chasing moves", "Spot trap wick", "Trade reversal only"],
      },
    ],
  },
  pm: {
    label: "New York PM",
    windows: ["PM1 12:00-13:30", "PM2 13:30-15:00", "PM3 15:00-16:30"],
    profiles: [
      {
        id: "pm-1",
        num: 1,
        title: "AM Trend or Reversal Recognition",
        marketConditions: ["Lunch flow thinning", "AM direction clear", "No major data"],
        keyCharacteristics: ["Continuation or fade", "Structure still valid", "Lower participation"],
        traderFocus: ["Confirm AM bias", "Reduce size midday", "Watch vwap"],
      },
      {
        id: "pm-2",
        num: 2,
        title: "Lunch Cycle Purge & Revert",
        marketConditions: ["Range bound lunch", "Stop hunt likely", "Thin books"],
        keyCharacteristics: ["Quick purge lows", "Snap back to mean", "Low conviction push"],
        traderFocus: ["Mark range extremes", "Fade purges", "Stay light"],
      },
      {
        id: "pm-3",
        num: 3,
        title: "Trending to Quick Reversal",
        marketConditions: ["Late session momentum", "Liquidity returns", "Close positioning"],
        keyCharacteristics: ["Late trend then reverse", "End of day spike", "Reversion into close"],
        traderFocus: ["Track last hour", "Fade exhaustion", "Manage exit tight"],
      },
    ],
  },
};
